[package]
name = "rust-two-sum-modified"
version = "0.1.0"
authors = ["Giovanni Dejan <giovanni.dejan@binus.ac.id>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
